#!/usr/bin/env python3
"""
generate_update_xml.py
Generates a Joomla update.xml file.

Required environment variables:
    VERSION       e.g. 1.2.3
    DOWNLOAD_URL  full URL to the ZIP file
    OUTPUT_PATH   path to write update.xml to

Optional:
    GENERATED     ISO-8601 timestamp (defaults to now)
"""
import os
import sys
from datetime import datetime, timezone

version      = os.environ.get("VERSION", "").strip()
download_url = os.environ.get("DOWNLOAD_URL", "").strip()
output_path  = os.environ.get("OUTPUT_PATH", ".joomla/update.xml").strip()
generated    = os.environ.get("GENERATED", datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"))

if not version or not download_url:
    print("ERROR: VERSION and DOWNLOAD_URL environment variables are required.", file=sys.stderr)
    sys.exit(1)

xml = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    f'<!-- Auto-generated by GitHub Actions on {generated} -->\n'
    '<updates>\n'
    '    <update>\n'
    '        <name>AMU IP Info</name>\n'
    '        <description>Displays the visitor IP address (IPv4 / IPv6) with optional Geo IP lookup.</description>\n'
    '        <element>mod_amu_ipinfo</element>\n'
    '        <type>module</type>\n'
    '        <client>site</client>\n'
    f'        <version>{version}</version>\n'
    '        <infourl title="AMU IP Info">https://github.com/Pierre-AmultisDev/amu_mod_ipinfo</infourl>\n'
    '        <downloads>\n'
    f'            <downloadurl type="full" format="zip">{download_url}</downloadurl>\n'
    '        </downloads>\n'
    '        <tags>\n'
    '            <tag>stable</tag>\n'
    '        </tags>\n'
    '        <maintainer>Amultis</maintainer>\n'
    '        <maintainerurl>https://amultis.dev</maintainerurl>\n'
    '        <targetplatform name="joomla" version="5.[0-9]+" />\n'
    '        <targetplatform name="joomla" version="6.[0-9]+" />\n'
    '        <php_minimum>8.1</php_minimum>\n'
    '    </update>\n'
    '</updates>\n'
)

# Ensure parent directory exists
os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else ".", exist_ok=True)

with open(output_path, "w", encoding="utf-8") as fh:
    fh.write(xml)

print(f"update.xml written to: {output_path}")
print(f"  version:      {version}")
print(f"  download_url: {download_url}")
