#!/usr/bin/env python3
"""
push_update_xml.py
Genereert update.xml en pusht het direct naar GitHub via de Contents API.
Geen git checkout/pull/push nodig.

Vereiste omgevingsvariabelen:
    GITHUB_TOKEN   Personal access token of GITHUB_TOKEN uit Actions
    VERSION        bijv. 1.2.3
    ZIP_NAME       bijv. mod_amu_ipinfo_v1.2.3.zip
"""
import os
import sys
import json
import base64
import urllib.request
import urllib.error
from datetime import datetime, timezone

REPO   = "Pierre-AmultisDev/amu_mod_ipinfo"
PATH   = "joomla/update.xml"
BRANCH = "master"

token    = os.environ.get("GITHUB_TOKEN", "").strip()
version  = os.environ.get("VERSION", "").strip()
zip_name = os.environ.get("ZIP_NAME", "").strip()

if not token or not version or not zip_name:
    print("ERROR: GITHUB_TOKEN, VERSION en ZIP_NAME zijn verplicht.", file=sys.stderr)
    sys.exit(1)

download_url = f"https://download.amultis.dev/joomla/modules/amu_ipinfo/{zip_name}"
generated    = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

xml = (
    '<?xml version="1.0" encoding="utf-8"?>\n'
    f'<!-- Auto-generated by GitHub Actions push_update_xml.py on {generated} -->\n'
    '<updates>\n'
    '    <!-- See also https://docs.joomla.org/Deploying_an_Update_Server -->\n'
    '    <update>\n'
    '        <!-- === REQUIRED TAG ELEMENTS == -->\n'
    '        <!-- ============================ -->\n'
    '\n'
    '        <!-- The name of the extension, this name will appear in the Name column of the Extension Manager's Update view -->\n'
    '        <name>aMultis IP Info</name>\n'
    '\n'
    '        <!-- The installed name of the extension -->\n'
    '        <element>mod_amu_ipinfo</element>\n'
    '\n'
    '        <!-- The type of extension (component, module, plugin, etc.) -->\n'
    '        <type>module</type>\n'
    '\n'
    '        <!-- The client of the extension -->\n'
    '        <client>"site"</client>\n'
    '\n'
    '        <!-- Definition of platform requirements -->\n'
    '        <targetplatform name="joomla" version="5|6" />\n'
    '\n'
    '        <!-- The version of the release -->\n'
    f'        <version>{version}</version>\n'
    '\n'
    '        <!-- A link to the xml file holding the changelog. -->\n'
    '        <!-- <changelogurl>https://download.amultis.dev/joomla/modules/amu_ipinfo/changelog.xml</changelogurl> -->\n'
    '\n'
    '        <downloads>\n'
    f'            <downloadurl type="full" format="zip">{download_url}</downloadurl>\n'
    '        </downloads>\n'
    '\n'
    '        <!-- === OPTIONAL TAG ELEMENTS == -->\n'
    '        <!-- ============================ -->\n'
    '        <!-- A short description of the extension (optional) -->\n'
    '        <description>Displays the visitor IP address (IPv4 / IPv6) with optional Geo IP lookup.</description>\n'
    '\n'
    '        <!-- A URL to point users to containing information about the update -->\n'
    '        <infourl title="aMultis IP Info">https://github.com/Pierre-AmultisDev/amu_mod_ipinfo</infourl>\n'
    '\n'
    '        <!-- The name of the extension maintainer (similar to the <author> tag in a manifest) -->\n'
    '        <maintainer>Pierre Veelen</maintainer>\n'
    '\n'
    '        <!-- The website of the extension maintainer (similar to the <authorUrl> tag in a manifest) -->\n'
    '        <maintainerurl>https://amultis.dev</maintainerurl>\n'
    '\n'
    '        <!-- Minimum supported PHP version can be supplied in the update stream -->\n'
    '        <php_minimum>8.1</php_minimum>\n'
    '\n'
    '        <tags>\n'
    '            <tag>stable</tag>\n'
    '        </tags>\n'
    '\n'
    '    </update>\n'
    '</updates>\n'
)

content_b64 = base64.b64encode(xml.encode()).decode()

headers = {
    "Authorization": f"Bearer {token}",
    "Accept": "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
}

api_url = f"https://api.github.com/repos/{REPO}/contents/{PATH}"

# Stap 1: haal de huidige SHA op (nodig om een bestaand bestand te overschrijven)
sha = None
try:
    req = urllib.request.Request(api_url, headers=headers)
    with urllib.request.urlopen(req) as resp:
        data = json.loads(resp.read())
        sha = data.get("sha")
        print(f"Bestaand bestand gevonden, SHA: {sha}")
except urllib.error.HTTPError as e:
    if e.code == 404:
        print("Bestand bestaat nog niet, wordt aangemaakt.")
    else:
        print(f"ERROR bij ophalen SHA: HTTP {e.code}", file=sys.stderr)
        sys.exit(1)

# Stap 2: PUT het nieuwe bestand
payload = {
    "message": f"chore: update.xml for v{version} [skip ci]",
    "content": content_b64,
    "branch": BRANCH,
}
if sha:
    payload["sha"] = sha

body = json.dumps(payload).encode()
req = urllib.request.Request(api_url, data=body, headers=headers, method="PUT")

try:
    with urllib.request.urlopen(req) as resp:
        http_code = resp.status
        print(f"update.xml succesvol bijgewerkt via GitHub API (HTTP {http_code})")
        print(f"  versie:       {version}")
        print(f"  download_url: {download_url}")
except urllib.error.HTTPError as e:
    body_resp = e.read().decode()
    print(f"ERROR: GitHub API gaf HTTP {e.code}", file=sys.stderr)
    print(body_resp, file=sys.stderr)
    sys.exit(1)
