#!/usr/bin/env python3
"""
update_xml.py
Genereert Joomla update.xml én changelog.xml en levert ze af op twee manieren:

  --github   Pusht bestanden naar GitHub via de Contents API
             Vereist: GITHUB_TOKEN, VERSION, ZIP_NAME
             Optioneel: PREV_TAG (vorige release tag voor changelog commits)

  --file     Schrijft bestanden naar lokale paden (op de server)
             Vereist: VERSION, ZIP_NAME, OUTPUT_PATH
             Optioneel: CHANGELOG_OUTPUT_PATH

Gemeenschappelijke omgevingsvariabelen:
    VERSION                  bijv. 1.2.3
    ZIP_NAME                 bijv. mod_amu_ipinfo_v1.2.3.zip
    PREV_TAG                 bijv. v1.2.2  (voor git log tussen releases)
    CHANGELOG_OUTPUT_PATH    pad voor changelog.xml op de server
"""
import os
import re
import sys
import json
import base64
import subprocess
import urllib.request
import urllib.error
from datetime import datetime, timezone

# ── Configuratie ─────────────────────────────────────────────────────────────
GITHUB_REPO        = "Pierre-AmultisDev/amu_mod_ipinfo"
GITHUB_BRANCH      = "master"
GITHUB_UPDATE_PATH = "update/update.xml"
GITHUB_CLOG_PATH   = "update/changelog.xml"
DOWNLOAD_BASE      = "https://download.amultis.dev/joomla/modules/amu_ipinfo"
CHANGELOG_URL      = "https://download.amultis.dev/joomla/modules/amu_ipinfo/changelog.xml"
ELEMENT            = "mod_amu_ipinfo"
EXT_TYPE           = "module"
# ─────────────────────────────────────────────────────────────────────────────

# ── Commit-bericht categorisering ────────────────────────────────────────────
# Gebaseerd op Conventional Commits (feat, fix, security, etc.)
CATEGORY_MAP = {
    'security': re.compile(r'^security(\(.*?\))?!?:', re.I),
    'fix':      re.compile(r'^fix(\(.*?\))?!?:',      re.I),
    'addition': re.compile(r'^feat(\(.*?\))?!?:',     re.I),
    'change':   re.compile(r'^(refactor|perf|style)(\(.*?\))?!?:', re.I),
    'remove':   re.compile(r'^(remove|revert)(\(.*?\))?!?:', re.I),
    'language': re.compile(r'^(lang|i18n|l10n)(\(.*?\))?!?:', re.I),
    'note':     re.compile(r'^(docs?|chore|ci|build|test)(\(.*?\))?!?:', re.I),
}

def categorize_commits(commits: list[str]) -> dict[str, list[str]]:
    """Verdeelt commit-berichten over Joomla changelog-categorieën."""
    result = {cat: [] for cat in CATEGORY_MAP}
    result['change'] = result.get('change', [])

    for msg in commits:
        msg = msg.strip()
        # Sla automatische CI-commits over
        if '[skip ci]' in msg or msg.startswith('chore: update'):
            continue
        matched = False
        for cat, pattern in CATEGORY_MAP.items():
            if pattern.match(msg):
                # Verwijder het prefix (feat: / fix: etc.) voor leesbaarheid
                clean = re.sub(r'^[^:]+:\s*', '', msg).strip()
                result[cat].append(clean)
                matched = True
                break
        if not matched and msg:
            # Niet-gecategoriseerde commits gaan naar 'change'
            result['change'].append(msg)

    return result


def get_commits_since(prev_tag: str) -> list[str]:
    """
    Haalt git commit-berichten op tussen prev_tag en HEAD.
    Werkt alleen als de repository uitgecheckt is (Job 2 / lokaal).
    """
    try:
        if prev_tag:
            cmd = ['git', 'log', f'{prev_tag}..HEAD', '--pretty=format:%s']
        else:
            # Geen vorige tag: pak commits van de laatste 50
            cmd = ['git', 'log', '-50', '--pretty=format:%s']
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        commits = [l.strip() for l in result.stdout.splitlines() if l.strip()]
        return commits
    except Exception as e:
        print(f"WAARSCHUWING: kon git log niet uitvoeren: {e}", file=sys.stderr)
        return []


def build_update_xml(version: str, download_url: str, sha256: str = '') -> str:
    """Bouw de volledige update.xml string op."""
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    checksum_line = f'        <sha256>{sha256}</sha256>\n' if sha256 else ''
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        f'<!-- Auto-generated by GitHub Actions update_xml.py on {generated} -->\n'
        '<updates>\n'
        '    <!-- See also https://docs.joomla.org/Deploying_an_Update_Server -->\n'
        '    <update>\n'
        '        <!-- === REQUIRED TAG ELEMENTS == -->\n'
        '        <!-- ============================ -->\n'
        '\n'
        '        <!-- The name of the extension -->\n'
        '        <name>aMultis IP Info</name>\n'
        '\n'
        '        <!-- The installed name of the extension -->\n'
        f'        <element>{ELEMENT}</element>\n'
        '\n'
        '        <!-- The type of extension (component, module, plugin, etc.) -->\n'
        f'        <type>{EXT_TYPE}</type>\n'
        '\n'
        '        <!-- The client of the extension -->\n'
        '        <client>site</client>\n'
        '\n'
        '        <!-- Definition of platform requirements -->\n'
        '        <targetplatform name="joomla" version="(5\..*|6\..*)\" />\n'
        '\n'
        '        <!-- The version of the release -->\n'
        f'        <version>{version}</version>\n'
        '\n'
        '        <!-- Link to the changelog -->\n'
        f'        <changelogurl>{CHANGELOG_URL}</changelogurl>\n'
        '\n'
        '        <downloads>\n'
        f'            <downloadurl type="full" format="zip">{download_url}</downloadurl>\n'
        '        </downloads>\n'
        '\n'
        f'{checksum_line}'
        '\n'
        '        <!-- === OPTIONAL TAG ELEMENTS == -->\n'
        '        <!-- ============================ -->\n'
        '\n'
        '        <!-- A short description of the extension -->\n'
        '        <description>Displays the visitor IP address (IPv4 / IPv6) with optional Geo IP lookup.</description>\n'
        '\n'
        '        <!-- A URL to point users to containing information about the update -->\n'
        '        <infourl title="aMultis IP Info">https://github.com/Pierre-AmultisDev/amu_mod_ipinfo</infourl>\n'
        '\n'
        '        <!-- The name of the extension maintainer -->\n'
        '        <maintainer>Pierre Veelen</maintainer>\n'
        '\n'
        '        <!-- The website of the extension maintainer -->\n'
        '        <maintainerurl>https://amultis.dev</maintainerurl>\n'
        '\n'
        '        <!-- Minimum supported PHP version -->\n'
        '        <php_minimum>8.1</php_minimum>\n'
        '\n'
        '        <tags>\n'
        '            <tag>stable</tag>\n'
        '        </tags>\n'
        '\n'
        '    </update>\n'
        '</updates>\n'
    )


def build_changelog_xml(version: str, categories: dict[str, list[str]],
                        existing_xml: str = '') -> str:
    """
    Bouw changelog.xml op. Voegt de nieuwe versie toe aan eventueel
    bestaande inhoud (zodat alle versies bewaard blijven).
    """
    generated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # Bouw de entries voor deze versie
    entries = ''
    for cat, items in categories.items():
        if not items:
            continue
        entries += f'        <{cat}>\n'
        for item in items:
            # Escape XML special chars
            safe = item.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
            entries += f'            <item>{safe}</item>\n'
        entries += f'        </{cat}>\n'

    # Als er geen commits zijn, voeg een generieke note toe
    if not entries:
        entries = f'        <note>\n            <item>Release {version}</item>\n        </note>\n'

    new_changelog = (
        f'    <changelog>\n'
        f'        <element>{ELEMENT}</element>\n'
        f'        <type>{EXT_TYPE}</type>\n'
        f'        <version>{version}</version>\n'
        f'{entries}'
        f'    </changelog>\n'
    )

    # Voeg toe aan bestaande inhoud als die er is
    if existing_xml and '<changelogs>' in existing_xml:
        # Verwijder de sluit-tag en voeg de nieuwe versie toe
        updated = existing_xml.replace(
            '</changelogs>',
            f'\n{new_changelog}</changelogs>\n'
        )
        return updated
    else:
        return (
            '<?xml version="1.0" encoding="utf-8"?>\n'
            f'<!-- Auto-generated by GitHub Actions update_xml.py on {generated} -->\n'
            '<changelogs>\n'
            f'\n{new_changelog}'
            '</changelogs>\n'
        )


def github_get_file(api_url: str, headers: dict) -> tuple[str, str | None]:
    """Haalt bestandsinhoud en SHA op via GitHub API. Geeft (content, sha)."""
    try:
        req = urllib.request.Request(api_url, headers=headers)
        with urllib.request.urlopen(req) as resp:
            data = json.loads(resp.read())
            sha     = data.get('sha')
            content = base64.b64decode(data.get('content', '')).decode('utf-8')
            return content, sha
    except urllib.error.HTTPError as e:
        if e.code == 404:
            return '', None
        raise


def github_put_file(api_url: str, headers: dict, content: str,
                    message: str, sha: str | None, branch: str):
    """Schrijft een bestand naar GitHub via de Contents API."""
    payload = {
        'message': message,
        'content': base64.b64encode(content.encode()).decode(),
        'branch':  branch,
    }
    if sha:
        payload['sha'] = sha

    body = json.dumps(payload).encode()
    req  = urllib.request.Request(api_url, data=body, headers=headers, method='PUT')
    try:
        with urllib.request.urlopen(req) as resp:
            print(f"  → GitHub API HTTP {resp.status}: {api_url.split('contents/')[-1]}")
    except urllib.error.HTTPError as e:
        print(f"ERROR: GitHub API gaf HTTP {e.code} voor {api_url}", file=sys.stderr)
        print(e.read().decode(), file=sys.stderr)
        sys.exit(1)


def mode_github(version: str, zip_name: str, prev_tag: str):
    """Pusht update.xml en changelog.xml naar GitHub via de Contents API."""
    token = os.environ.get('GITHUB_TOKEN', '').strip()
    if not token:
        print("ERROR: GITHUB_TOKEN is verplicht voor --github modus.", file=sys.stderr)
        sys.exit(1)

    sha256 = os.environ.get('SHA256', '').strip()

    headers = {
        'Authorization': f'Bearer {token}',
        'Accept':        'application/vnd.github+json',
        'Content-Type':  'application/json',
        'X-GitHub-Api-Version': '2022-11-28',
    }
    base_url = f'https://api.github.com/repos/{GITHUB_REPO}/contents'

    # ── update.xml ──────────────────────────────────────────────────────────
    print(f"Genereer update.xml voor v{version}...")
    download_url = f'{DOWNLOAD_BASE}/{zip_name}'
    update_xml   = build_update_xml(version, download_url, sha256)
    if sha256:
        print(f"  SHA256 checksum: {sha256}")
    else:
        print("  WAARSCHUWING: geen SHA256 checksum opgegeven.", file=sys.stderr)

    _, update_sha = github_get_file(f'{base_url}/{GITHUB_UPDATE_PATH}', headers)
    if update_sha:
        print(f"  Bestaande update.xml gevonden (SHA: {update_sha})")
    else:
        print("  update.xml wordt nieuw aangemaakt.")

    github_put_file(
        f'{base_url}/{GITHUB_UPDATE_PATH}', headers, update_xml,
        f'chore: update.xml for v{version} [skip ci]',
        update_sha, GITHUB_BRANCH
    )

    # ── changelog.xml ───────────────────────────────────────────────────────
    print(f"\nGenereer changelog.xml voor v{version}...")
    commits = get_commits_since(prev_tag)
    print(f"  {len(commits)} commits gevonden since {prev_tag or 'begin'}.")

    categories = categorize_commits(commits)
    for cat, items in categories.items():
        if items:
            print(f"  {cat}: {len(items)} item(s)")

    existing_clog, clog_sha = github_get_file(f'{base_url}/{GITHUB_CLOG_PATH}', headers)
    if clog_sha:
        print(f"  Bestaande changelog.xml gevonden (SHA: {clog_sha})")
    else:
        print("  changelog.xml wordt nieuw aangemaakt.")

    changelog_xml = build_changelog_xml(version, categories, existing_clog)
    github_put_file(
        f'{base_url}/{GITHUB_CLOG_PATH}', headers, changelog_xml,
        f'chore: changelog.xml for v{version} [skip ci]',
        clog_sha, GITHUB_BRANCH
    )

    # ── mod_amu_ipinfo.xml versienummer bijwerken ───────────────────────────
    if os.environ.get('PATCH_MANIFEST', '').lower() == 'true':
        print(f"\nPatch versienummer in src/mod_amu_ipinfo/mod_amu_ipinfo.xml...")
        manifest_path = "src/mod_amu_ipinfo/mod_amu_ipinfo.xml"
        manifest_api  = f'{base_url}/{manifest_path}'

        try:
            manifest_content, manifest_sha = github_get_file(manifest_api, headers)
            if manifest_content:
                import re
                updated = re.sub(
                    r'<version>.*?</version>',
                    f'<version>{version}</version>',
                    manifest_content,
                    count=1
                )
                if updated != manifest_content:
                    github_put_file(
                        manifest_api, headers, updated,
                        f'chore: bump version to {version} in mod_amu_ipinfo.xml [skip ci]',
                        manifest_sha, GITHUB_BRANCH
                    )
                    print(f"  mod_amu_ipinfo.xml bijgewerkt naar versie {version}")
                else:
                    print(f"  mod_amu_ipinfo.xml: versie was al {version}")
            else:
                print("  WAARSCHUWING: mod_amu_ipinfo.xml niet gevonden op GitHub", file=sys.stderr)
        except Exception as e:
            print(f"  WAARSCHUWING: kon manifest niet patchen: {e}", file=sys.stderr)

    print(f"\nKlaar! update.xml en changelog.xml bijgewerkt voor v{version}.")


def mode_file(version: str, zip_name: str, prev_tag: str):
    """Schrijft update.xml en changelog.xml naar lokale paden op de server."""
    output_path     = os.environ.get('OUTPUT_PATH', '').strip()
    clog_output     = os.environ.get('CHANGELOG_OUTPUT_PATH', '').strip()

    if not output_path:
        print("ERROR: OUTPUT_PATH is verplicht voor --file modus.", file=sys.stderr)
        sys.exit(1)

    # ── update.xml ──────────────────────────────────────────────────────────
    sha256       = os.environ.get('SHA256', '').strip()
    download_url = f'{DOWNLOAD_BASE}/{zip_name}'
    update_xml   = build_update_xml(version, download_url, sha256)
    os.makedirs(os.path.dirname(output_path) if os.path.dirname(output_path) else '.', exist_ok=True)
    with open(output_path, 'w', encoding='utf-8') as fh:
        fh.write(update_xml)
    print(f"update.xml geschreven naar: {output_path}")

    # ── changelog.xml ───────────────────────────────────────────────────────
    if clog_output:
        commits = get_commits_since(prev_tag)
        categories = categorize_commits(commits)

        existing_clog = ''
        if os.path.exists(clog_output):
            with open(clog_output, encoding='utf-8') as fh:
                existing_clog = fh.read()

        changelog_xml = build_changelog_xml(version, categories, existing_clog)
        os.makedirs(os.path.dirname(clog_output) if os.path.dirname(clog_output) else '.', exist_ok=True)
        with open(clog_output, 'w', encoding='utf-8') as fh:
            fh.write(changelog_xml)
        print(f"changelog.xml geschreven naar: {clog_output}")
    else:
        print("CHANGELOG_OUTPUT_PATH niet ingesteld — changelog.xml overgeslagen.")

    print(f"\nKlaar! Versie: {version} | Download: {download_url}")


# ── Main ─────────────────────────────────────────────────────────────────────
if len(sys.argv) < 2 or sys.argv[1] not in ('--github', '--file'):
    print("Gebruik: update_xml.py --github | --file", file=sys.stderr)
    sys.exit(1)

version  = os.environ.get('VERSION',  '').strip()
zip_name = os.environ.get('ZIP_NAME', '').strip()
prev_tag = os.environ.get('PREV_TAG', '').strip()

if not version or not zip_name:
    print("ERROR: VERSION en ZIP_NAME zijn verplicht.", file=sys.stderr)
    sys.exit(1)

if sys.argv[1] == '--github':
    mode_github(version, zip_name, prev_tag)
else:
    mode_file(version, zip_name, prev_tag)
